import type { Metadata } from "next";
import "../styles/globals.css";
import { poppins } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Form Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`${poppins.className} scroll-smooth`}>
        {children}
      </body>
    </html>
  );
}
